service: yuyat-serverless-ruby-practice

provider:
  name: aws
  runtime: ruby2.5
  region: ap-northeast-1

functions:
  hello:
    handler: handler.hello
    role: ${env:AWS_LAMBDA_IAM_ROLE}
    events:
      - http:
          path: hello
          method: get
